[package]
name = "interop-tests"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[dependencies]
bellows = { workspace = true, features = ["postgres"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive", "std"] }
tokio = { workspace = true, features = ["io-util", "macros", "process", "rt-multi-thread", "sync", "time"] }

[dev-dependencies]
serde_json.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "process", "rt-multi-thread", "sync", "time"] }
